server:
  port: ${PORT}

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    url: "jdbc:postgresql://${DB_SERVER}:${DB_SERVER_PORT}/${DB_NAME}?sslMode=${DB_SSL_MODE:require}"
    user: ${DB_USER}
    password: ${DB_PASS}
  datasource:
    hikari:
      connectionTestQuery: SELECT 1
      poolName: pool
      maximumPoolSize: 50
      minimumIdle: 1
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_SERVER}:${DB_SERVER_PORT}/${DB_NAME}?sslMode=${DB_SSL_MODE:require}"
    username: ${DB_USER}
    password: ${DB_PASS}
  h2.console.enabled: false

